apiVersion: v1
kind: Template
metadata:
  name: turbine-server
  annotations:
    openshift.io/display-name: Turbine Server
    description: Application containing Turbine server
    tags: turbine
    iconClass: icon-shadowman
    template.openshift.io/long-description: Application containing Turbine server
    template.openshift.io/provider-display-name: Red Hat, Inc.
labels:
  template: turbine-server
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: turbine-server
    labels:
      app: turbine-server
- apiVersion: v1
  kind: Service
  metadata:
    name: turbine-server
    labels:
      app: turbine-server
  spec:
    type: LoadBalancer
    selector:
      app: turbine-server
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: turbine-server
    labels:
      app: turbine-server
  spec:
    replicas: 1
    selector:
      app: turbine-server
    strategy:
      type: Rolling
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
    template:
      metadata:
        labels:
          app: turbine-server
      spec:
        serviceAccountName: turbine-server
        containers:
        - name: turbine-server
          image: fabric8/turbine-server:1.0.28
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 180
    triggers:
    - type: ConfigChange
